/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alard
 */

package view;

import controller.AccountController;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import controller.BusinessController;
import model.Account;
import model.BusinessInput;
import model.BusinessLine;
import model.PermitNo;
import model.Service;

public class Step3 extends javax.swing.JPanel {

        BusinessInput bi;
        Account ac = new Account();
        MainFrame parentFrame;
        BusinessController bcon = new BusinessController();
        AccountController acon = new AccountController();
        
        ArrayList<String> businessLineInput = new ArrayList<>();
        ArrayList<String> serviceInput = new ArrayList<>();
        ArrayList<Integer> permitInput = new ArrayList<>();
        ArrayList<BusinessLine> businessLineObject = new ArrayList<>();
        ArrayList<Service> serviceObject = new ArrayList<>();
        ArrayList<PermitNo> permitObject = new ArrayList<>();
    
        public Step3(Account ac, BusinessInput bi, MainFrame parentFrame) {
            initComponents();
            this.ac = ac;
            this.bi = bi;
            this.parentFrame = parentFrame; 
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LineBusiness = new javax.swing.JLabel();
        LineName = new javax.swing.JLabel();
        LineNameField = new javax.swing.JTextField();
        Service = new javax.swing.JLabel();
        ServiceField = new javax.swing.JTextField();
        PermitNoLabel = new javax.swing.JLabel();
        PermitNoField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        AddMoreButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();

    
        setMaximumSize(new java.awt.Dimension(931, 601));
        setMinimumSize(new java.awt.Dimension(931, 601));

        jPanel1.setBackground(new java.awt.Color(221, 230, 237));

        LineBusiness.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/UPDATED_GUI_Logos/QCBPH_LOB (200 x 50 px).png"))); // NOI18N

        LineName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        LineName.setForeground(new java.awt.Color(39, 55, 77));
        LineName.setText("Business Line Name:");

        Service.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Service.setForeground(new java.awt.Color(39, 55, 77));
        Service.setText("Service Name:");

        PermitNoLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PermitNoLabel.setForeground(new java.awt.Color(39, 55, 77));
        PermitNoLabel.setText("Permit No:");

        BackButton.setBackground(new java.awt.Color(82, 109, 130));
        BackButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(221, 230, 237));
        BackButton.setText("Back");

        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        AddMoreButton.setBackground(new java.awt.Color(82, 109, 130));
        AddMoreButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AddMoreButton.setForeground(new java.awt.Color(221, 230, 237));
        AddMoreButton.setText("Add More");

        AddMoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMoreButtonActionPerformed(evt);
            }
        });

        DoneButton.setBackground(new java.awt.Color(82, 109, 130));
        DoneButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        DoneButton.setForeground(new java.awt.Color(221, 230, 237));
        DoneButton.setText("Done");

        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LineName)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PermitNoField)
                            .addComponent(ServiceField)
                            .addComponent(LineNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Service)
                    .addComponent(PermitNoLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(BackButton)
                        .addGap(149, 149, 149)
                        .addComponent(AddMoreButton)
                        .addGap(154, 154, 154)
                        .addComponent(DoneButton)))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LineBusiness)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(LineBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LineName)
                    .addComponent(LineNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Service)
                    .addComponent(ServiceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PermitNoLabel)
                    .addComponent(PermitNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(AddMoreButton)
                    .addComponent(DoneButton))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {
        parentFrame.showCard("step2");
    }

    private void AddMoreButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Validate input fields before adding
        if (LineNameField.getText().isEmpty() || ServiceField.getText().isEmpty() || PermitNoField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Business Line Name, Service Name, and Permit No are required.");
            return;
        }
        
        businessLineInput.add(LineNameField.getText());
        serviceInput.add(ServiceField.getText());
        permitInput.add(Integer.valueOf(PermitNoField.getText()));

        int option = JOptionPane.showConfirmDialog(this, "Do you want to add more?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            // Clear fields for next input
            LineNameField.setText("");
            ServiceField.setText("");
            PermitNoField.setText("");
        }
        // If No, do nothing, and the fields will retain their input
    }

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Validate input fields one last time
        if (LineNameField.getText().isEmpty() || ServiceField.getText().isEmpty() || PermitNoField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Business Line Name, Service Name, and Permit No are required.");
            return;
        }
        
        businessLineInput.add(LineNameField.getText());
        serviceInput.add(ServiceField.getText());
        permitInput.add(Integer.valueOf(PermitNoField.getText()));

        // Confirm submission
        int option = JOptionPane.showConfirmDialog(this, "Submit this application?", "Confirm Submission", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.NO_OPTION) {
        // Do nothing and just close the dialog
        return;
    }

        for (String s: businessLineInput) {
            BusinessLine b = new BusinessLine();
            b.setBusinessLineName(s);
            businessLineObject.add(b);   
        }

        for (String s: serviceInput) {
            Service c = new Service();
            c.setServiceName(s);
            serviceObject.add(c);  
        }
        
        for (Integer s: permitInput) {
            PermitNo c = new PermitNo();
            c.setPermitNo(s);
            permitObject.add(c);  
        }

        bi.setBusinessLine(businessLineObject);
        bi.setService(serviceObject);
        bi.setPermitNo(permitObject);
         
        
        bcon.insertBusinessInfo(bi);
        bcon.insertBusinessMain(bi);
        acon.updateRegNum(bi, ac);
        ac.setRegNum(bi.getRegistrationNum());


        JOptionPane.showMessageDialog(this, "Application submitted successfully!");
        
        parentFrame.setHomeStatus(bcon.readStatus(bi.getRegistrationNum()), ac);

        parentFrame.showCard("homeStatus");
        
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMoreButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel LineBusiness;
    private javax.swing.JLabel LineName;
    private javax.swing.JTextField LineNameField;
    private javax.swing.JTextField PermitNoField;
    private javax.swing.JLabel PermitNoLabel;
    private javax.swing.JLabel Service;
    private javax.swing.JTextField ServiceField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
